### ISSUE TITLE
ros2 humble fake driver does not stop the robot when no input is given

### ISSUE THREAD

**Issue by kruusamae** [robotont/robotont_driver#17]
@Veix123 @patsyuk03 
the fake driver on humble-devel branch does not appear to have a timeout and stop moving when no new input arrives from teleop. right now the robot keeps on moving infinitely

**Comment by kruusamae** [comment]
@patsyuk03 
i did not see this issue being solved on humble-devel branch. i test with turtlesim package and turtle_teleop_key node. i issue the following command, and even when i press the arrow key once, the robotont robot moves endlessly, no new messages are being published.
`ros2 run  turtlesim turtle_teleop_key --rosargs --remap turtle1/cmd_vel:=cmd_vel`

**Comment by patsyuk03** [comment]
@kruusamae can you try now?

**Comment by kruusamae** [comment]
now it works!
