### ISSUE TITLE
get prefix from param server

### ISSUE THREAD

**Issue by kruusamae** [robotont/robotont_driver#8]
for odom links, get prefix from param server. the prefix can be uploaded in the yaml-file or launch-file. ideally, it's the same prefix that is propagated with __ns.

**Comment by kruusamae** [comment]
@Veix123 kas see lahendus oleks jätkuvalt loogiline? isegi nüüd, kus prefixi parsimine sai lahendatud yaml-faili jaoks? kui ei, siis paneks issue praegu kinni

**Comment by Veix123** [comment]
Paneme lukku jah kuniks järgmise kohapealt vastu näppe saame ;)
